
language: c

os:
    - linux
    - osx

sudo: required
dist: trusty
script: make
compiler:
  - gcc
  
install:
    - echo $TRAVIS_OS_NAME
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; sudo apt-get install gfortran; sudo apt-get install -y libatlas-base-dev; fi
      # build and test library
    - make
    - (cd demo/; ./demoIRWLS.sh)

  
  
